name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Show directory structure
      run: ls -la
    
    - name: Build app for simulator
      run: |
        xcodebuild \
          -project SheepFarm.xcodeproj \
          -scheme SheepFarm \
          -sdk iphonesimulator \
          -configuration Debug \
          -derivedDataPath DerivedData \
          build
    
    - name: Build IPA for device
      run: |
        xcodebuild \
          -project SheepFarm.xcodeproj \
          -scheme SheepFarm \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          build
    
    - name: Create IPA
      run: |
        cd DerivedData/Build/Products/Release-iphoneos
        mkdir Payload
        cp -r SheepFarm.app Payload/
        zip -r SheepFarm.ipa Payload
        rm -rf Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: SheepFarm-IPA
        path: DerivedData/Build/Products/Release-iphoneos/SheepFarm.ipa
        
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: SheepFarm-App
        path: DerivedData/Build/Products/Release-iphoneos/SheepFarm.app
