name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcodebuild -version
    
    - name: Build app for simulator
      run: |
        cd IdleClicker
        xcodebuild \
          -project IdleClicker.xcodeproj \
          -scheme IdleClicker \
          -sdk iphonesimulator \
          -configuration Debug \
          -derivedDataPath DerivedData \
          build
    
    - name: Build IPA for device
      run: |
        cd IdleClicker
        xcodebuild \
          -project IdleClicker.xcodeproj \
          -scheme IdleClicker \
          -sdk iphoneos \
          -configuration Release \
          -derivedDataPath DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          build
    
    - name: Create IPA
      run: |
        cd IdleClicker/DerivedData/Build/Products/Release-iphoneos
        mkdir Payload
        cp -r IdleClicker.app Payload/
        zip -r IdleClicker.ipa Payload
        rm -rf Payload
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: IdleClicker-IPA
        path: IdleClicker/DerivedData/Build/Products/Release-iphoneos/IdleClicker.ipa
        
    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: IdleClicker-App
        path: IdleClicker/DerivedData/Build/Products/Release-iphoneos/IdleClicker.app